USE Py;
CREATE TABLE Location 
(
    country	VARCHAR(512),
    city	VARCHAR(512),
    state	VARCHAR(512),
    postal_code	INT
);

INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Henderson', 'Kentucky', '42420');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Los Angeles', 'California', '90036');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fort Lauderdale', 'Florida', '33311');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Los Angeles', 'California', '90032');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Concord', 'North Carolina', '28027');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Seattle', 'Washington', '98103');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fort Worth', 'Texas', '76106');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Madison', 'Wisconsin', '53711');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'West Jordan', 'Utah', '84084');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Francisco', 'California', '94109');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fremont', 'Nebraska', '68025');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Philadelphia', 'Pennsylvania', '19140');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Orem', 'Utah', '84057');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Los Angeles', 'California', '90049');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Houston', 'Texas', '77095');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Richardson', 'Texas', '75080');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Houston', 'Texas', '77041');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Naperville', 'Illinois', '60540');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Melbourne', 'Florida', '32935');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Eagan', 'Minnesota', '55122');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Westland', 'Michigan', '48185');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dover', 'Delaware', '19901');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'New Albany', 'Indiana', '47150');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'New York City', 'New York', '10024');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Troy', 'New York', '12180');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Los Angeles', 'California', '90004');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chicago', 'Illinois', '60610');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Gilbert', 'Arizona', '85234');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Springfield', 'Virginia', '22153');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'New York City', 'New York', '10009');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Jackson', 'Michigan', '49201');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Memphis', 'Tennessee', '38109');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Houston', 'Texas', '77070');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Decatur', 'Alabama', '35601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Francisco', 'California', '94122');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Durham', 'North Carolina', '27707');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chicago', 'Illinois', '60623');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Columbia', 'South Carolina', '29203');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rochester', 'Minnesota', '55901');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Minneapolis', 'Minnesota', '55407');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Portland', 'Oregon', '97206');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Saint Paul', 'Minnesota', '55106');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Aurora', 'Colorado', '80013');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Charlotte', 'North Carolina', '28205');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Orland Park', 'Illinois', '60462');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'New York City', 'New York', '10035');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Urbandale', 'Iowa', '50322');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Columbus', 'Ohio', '43229');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bristol', 'Tennessee', '37620');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Wilmington', 'Delaware', '19805');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bloomington', 'Illinois', '61701');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Phoenix', 'Arizona', '85023');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Roseville', 'California', '95661');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Independence', 'Missouri', '64055');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pasadena', 'California', '91104');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Newark', 'Ohio', '43055');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Franklin', 'Wisconsin', '53132');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Scottsdale', 'Arizona', '85254');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Jose', 'California', '95123');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Seattle', 'Washington', '98105');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Seattle', 'Washington', '98115');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Edmond', 'Oklahoma', '73034');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Los Angeles', 'California', '90045');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Philadelphia', 'Pennsylvania', '19134');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Carlsbad', 'New Mexico', '88220');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Antonio', 'Texas', '78207');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Houston', 'Texas', '77036');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Decatur', 'Illinois', '62521');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Monroe', 'Louisiana', '71203');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fairfield', 'Connecticut', '6824');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Grand Prairie', 'Texas', '75051');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Redlands', 'California', '92374');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hamilton', 'Ohio', '45011');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Westfield', 'New Jersey', '7090');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Philadelphia', 'Pennsylvania', '19120');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Akron', 'Ohio', '44312');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Denver', 'Colorado', '80219');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dallas', 'Texas', '75220');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Franklin', 'Tennessee', '37064');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Whittier', 'California', '90604');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Saginaw', 'Michigan', '48601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Medina', 'Ohio', '44256');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dublin', 'Ohio', '43017');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Detroit', 'Michigan', '48227');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Columbia', 'Tennessee', '38401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tampa', 'Florida', '33614');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Santa Clara', 'California', '95051');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lakeville', 'Minnesota', '55044');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Diego', 'California', '92037');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pasadena', 'Texas', '77506');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Brentwood', 'California', '94513');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chapel Hill', 'North Carolina', '27514');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Morristown', 'New Jersey', '7960');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cincinnati', 'Ohio', '45231');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Francisco', 'California', '94110');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Inglewood', 'California', '90301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tamarac', 'Florida', '33319');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Colorado Springs', 'Colorado', '80906');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Belleville', 'New Jersey', '7109');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Taylor', 'Michigan', '48180');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lakewood', 'New Jersey', '8701');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Arlington', 'Virginia', '22204');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Arvada', 'Colorado', '80004');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hackensack', 'New Jersey', '7601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Saint Petersburg', 'Florida', '33710');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Philadelphia', 'Pennsylvania', '19143');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Long Beach', 'California', '90805');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hesperia', 'California', '92345');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Murfreesboro', 'Tennessee', '37130');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Layton', 'Utah', '84041');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Austin', 'Texas', '78745');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lowell', 'Massachusetts', '1852');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Columbus', 'Georgia', '31907');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Manchester', 'Connecticut', '6040');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Harlingen', 'Texas', '78550');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tucson', 'Arizona', '85705');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Quincy', 'Illinois', '62301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Franklin', 'Massachusetts', '2038');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pembroke Pines', 'Florida', '33024');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Des Moines', 'Washington', '98198');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Peoria', 'Illinois', '61604');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Las Vegas', 'Nevada', '89115');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Warwick', 'Rhode Island', '2886');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Miami', 'Florida', '33180');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Wilmington', 'North Carolina', '28403');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Huntington Beach', 'California', '92646');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Richmond', 'Kentucky', '40475');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Louisville', 'Colorado', '80027');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lawrence', 'Massachusetts', '1841');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Jackson', 'Mississippi', '39212');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Canton', 'Michigan', '48187');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'New Rochelle', 'New York', '10801');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Gastonia', 'North Carolina', '28052');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Jacksonville', 'Florida', '32216');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Columbus', 'Indiana', '47201');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Auburn', 'New York', '13021');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Norman', 'Oklahoma', '73071');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Concord', 'California', '94521');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Park Ridge', 'Illinois', '60068');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Amarillo', 'Texas', '79109');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lindenhurst', 'New York', '11757');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Los Angeles', 'California', '90008');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Diego', 'California', '92024');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Huntsville', 'Texas', '77340');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rochester', 'New York', '14609');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fayetteville', 'Arkansas', '72701');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Costa Mesa', 'California', '92627');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Parker', 'Colorado', '80134');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Atlanta', 'Georgia', '30318');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Gladstone', 'Missouri', '64118');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Great Falls', 'Montana', '59405');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Detroit', 'Michigan', '48234');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lakeland', 'Florida', '33801');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Montgomery', 'Alabama', '36116');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mesa', 'Arizona', '85204');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chicago', 'Illinois', '60653');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Green Bay', 'Wisconsin', '54302');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Springfield', 'Ohio', '45503');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Anaheim', 'California', '92804');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Marysville', 'Washington', '98270');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Salem', 'Oregon', '97301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Laredo', 'Texas', '78041');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dallas', 'Texas', '75217');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Grove City', 'Ohio', '43123');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'New York City', 'New York', '10011');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dearborn', 'Michigan', '48126');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Warner Robins', 'Georgia', '31088');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Vallejo', 'California', '94591');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mission Viejo', 'California', '92691');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rochester Hills', 'Michigan', '48307');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Plainfield', 'New Jersey', '7060');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Sierra Vista', 'Arizona', '85635');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Vancouver', 'Washington', '98661');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Aurora', 'Illinois', '60505');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Arlington', 'Texas', '76017');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Louisville', 'Kentucky', '40214');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dallas', 'Texas', '75081');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cleveland', 'Ohio', '44105');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tyler', 'Texas', '75701');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Burlington', 'North Carolina', '27217');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Waynesboro', 'Virginia', '22980');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chester', 'Pennsylvania', '19013');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cary', 'North Carolina', '27511');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Palm Coast', 'Florida', '32137');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mount Vernon', 'New York', '10550');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Detroit', 'Michigan', '48205');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hialeah', 'Florida', '33012');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Oceanside', 'New York', '11572');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Diego', 'California', '92105');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Evanston', 'Illinois', '60201');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Trenton', 'Michigan', '48183');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cottage Grove', 'Minnesota', '55016');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bossier City', 'Louisiana', '71111');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Des Moines', 'Iowa', '50315');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lancaster', 'California', '93534');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Richmond', 'Virginia', '23223');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Asheville', 'North Carolina', '28806');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lake Elsinore', 'California', '92530');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Omaha', 'Nebraska', '68104');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Edmonds', 'Washington', '98026');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Santa Ana', 'California', '92704');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Milwaukee', 'Wisconsin', '53209');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Florence', 'Kentucky', '41042');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lorain', 'Ohio', '44052');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Linden', 'New Jersey', '7036');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Salinas', 'California', '93905');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'New Brunswick', 'New Jersey', '8901');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lancaster', 'Pennsylvania', '17602');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Concord', 'New Hampshire', '3301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Columbia', 'Maryland', '21044');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Garland', 'Texas', '75043');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Norwich', 'Connecticut', '6360');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Alexandria', 'Virginia', '22304');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Toledo', 'Ohio', '43615');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Farmington', 'New Mexico', '87401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Riverside', 'California', '92503');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Torrance', 'California', '90503');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Round Rock', 'Texas', '78664');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Oceanside', 'California', '92054');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Boca Raton', 'Florida', '33433');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Virginia Beach', 'Virginia', '23464');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Murrieta', 'California', '92563');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Jacksonville', 'North Carolina', '28540');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Burlington', 'Iowa', '52601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Olympia', 'Washington', '98502');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Washington', 'District of Columbia', '20016');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Jefferson City', 'Missouri', '65109');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Saint Peters', 'Missouri', '63376');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rockford', 'Illinois', '61107');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Miami', 'Florida', '33142');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Brownsville', 'Texas', '78521');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Yonkers', 'New York', '10701');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Oakland', 'California', '94601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Monroe', 'North Carolina', '28110');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Clinton', 'Maryland', '20735');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Encinitas', 'California', '92024');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Roswell', 'Georgia', '30076');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Jonesboro', 'Arkansas', '72401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Richmond', 'Indiana', '47374');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Antioch', 'California', '94509');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Homestead', 'Florida', '33030');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'La Porte', 'Indiana', '46350');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lansing', 'Michigan', '48911');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cuyahoga Falls', 'Ohio', '44221');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Reno', 'Nevada', '89502');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Harrisonburg', 'Virginia', '22801');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Escondido', 'California', '92025');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Royal Oak', 'Michigan', '48073');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rockville', 'Maryland', '20852');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Coral Springs', 'Florida', '33065');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Buffalo', 'New York', '14215');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Boynton Beach', 'Florida', '33437');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Gulfport', 'Mississippi', '39503');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fresno', 'California', '93727');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Greenville', 'North Carolina', '27834');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Long Beach', 'New York', '11561');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Florence', 'Alabama', '35630');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Macon', 'Georgia', '31204');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cedar Rapids', 'Iowa', '52402');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Providence', 'Rhode Island', '2908');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pueblo', 'Colorado', '81001');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fairfield', 'California', '94533');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Deltona', 'Florida', '32725');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Murray', 'Kentucky', '42071');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Middletown', 'Connecticut', '6457');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Freeport', 'New York', '11520');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pico Rivera', 'California', '90660');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Provo', 'Utah', '84604');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pleasant Grove', 'Utah', '84062');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Smyrna', 'Georgia', '30080');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Salem', 'Virginia', '24153');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Parma', 'Ohio', '44134');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mobile', 'Alabama', '36608');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'New Bedford', 'Massachusetts', '2740');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Irving', 'Texas', '75061');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Vineland', 'New Jersey', '8360');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Glendale', 'Arizona', '85301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Niagara Falls', 'New York', '14304');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Thomasville', 'North Carolina', '27360');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Westminster', 'California', '92683');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Jackson', 'Tennessee', '38301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Coppell', 'Texas', '75019');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pomona', 'California', '91767');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'North Las Vegas', 'Nevada', '89031');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Allentown', 'Pennsylvania', '18103');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Newark', 'Delaware', '19711');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tempe', 'Arizona', '85281');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Laguna Niguel', 'California', '92677');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bridgeton', 'New Jersey', '8302');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Everett', 'Massachusetts', '2149');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Watertown', 'New York', '13601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Appleton', 'Wisconsin', '54915');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bellevue', 'Washington', '98006');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Allen', 'Texas', '75002');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'El Paso', 'Texas', '79907');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Grapevine', 'Texas', '76051');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Carrollton', 'Texas', '75007');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Smyrna', 'Tennessee', '37167');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Kent', 'Washington', '98031');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lafayette', 'Louisiana', '70506');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tigard', 'Oregon', '97224');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Skokie', 'Illinois', '60076');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Plano', 'Texas', '75023');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Suffolk', 'Virginia', '23434');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Indianapolis', 'Indiana', '46203');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bayonne', 'New Jersey', '7002');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fayetteville', 'North Carolina', '28314');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Greensboro', 'North Carolina', '27405');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Baltimore', 'Maryland', '21215');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Kenosha', 'Wisconsin', '53142');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Olathe', 'Kansas', '66062');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Auburn', 'Washington', '98002');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tulsa', 'Oklahoma', '74133');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Redmond', 'Oregon', '97756');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Raleigh', 'North Carolina', '27604');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Muskogee', 'Oklahoma', '74403');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Meriden', 'Connecticut', '6450');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bowling Green', 'Kentucky', '42104');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'South Bend', 'Indiana', '46614');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bristol', 'Connecticut', '6010');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Henderson', 'Nevada', '89015');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Spokane', 'Washington', '99207');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Keller', 'Texas', '76248');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fairfield', 'Ohio', '45014');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Port Orange', 'Florida', '32127');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Medford', 'Oregon', '97504');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Charlottesville', 'Virginia', '22901');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Missoula', 'Montana', '59801');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Miami', 'Florida', '33178');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Florence', 'South Carolina', '29501');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Springfield', 'Oregon', '97477');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Apopka', 'Florida', '32712');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Reading', 'Pennsylvania', '19601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Broomfield', 'Colorado', '80020');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Springfield', 'Missouri', '65807');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Paterson', 'New Jersey', '7501');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Oklahoma City', 'Oklahoma', '73120');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chesapeake', 'Virginia', '23320');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lubbock', 'Texas', '79424');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Columbia', 'Missouri', '65203');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Johnson City', 'Tennessee', '37604');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Auburn', 'Alabama', '36830');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Bernardino', 'California', '92404');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Leominster', 'Massachusetts', '1453');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bozeman', 'Montana', '59715');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Peoria', 'Arizona', '85345');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lakewood', 'Ohio', '44107');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Perth Amboy', 'New Jersey', '8861');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Ontario', 'California', '91761');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rancho Cucamonga', 'California', '91730');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Moorhead', 'Minnesota', '56560');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mesquite', 'Texas', '75150');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Stockton', 'California', '95207');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Ormond Beach', 'Florida', '32174');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Sunnyvale', 'California', '94086');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dover', 'New Hampshire', '3820');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'York', 'Pennsylvania', '17403');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'College Station', 'Texas', '77840');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Saint Louis', 'Missouri', '63116');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Quincy', 'Massachusetts', '2169');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Manteca', 'California', '95336');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Kent', 'Ohio', '44240');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Angelo', 'Texas', '76903');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Salt Lake City', 'Utah', '84106');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Huntsville', 'Alabama', '35810');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Knoxville', 'Tennessee', '37918');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Little Rock', 'Arkansas', '72209');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lincoln Park', 'Michigan', '48146');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Marion', 'Ohio', '43302');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Littleton', 'Colorado', '80122');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Burlington', 'Vermont', '5408');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bangor', 'Maine', '4401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Southaven', 'Mississippi', '38671');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'New Castle', 'Indiana', '47362');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Midland', 'Michigan', '48640');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Sioux Falls', 'South Dakota', '57103');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fort Collins', 'Colorado', '80525');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lafayette', 'Indiana', '47905');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Clarksville', 'Tennessee', '37042');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Sacramento', 'California', '95823');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Thousand Oaks', 'California', '91360');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Malden', 'Massachusetts', '2148');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Holyoke', 'Massachusetts', '1040');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Albuquerque', 'New Mexico', '87105');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Sparks', 'Nevada', '89431');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Coachella', 'California', '92236');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Elmhurst', 'Illinois', '60126');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Passaic', 'New Jersey', '7055');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'North Charleston', 'South Carolina', '29406');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Newport News', 'Virginia', '23602');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Jamestown', 'New York', '14701');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mishawaka', 'Indiana', '46544');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bowling Green', 'Ohio', '43402');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'La Quinta', 'California', '92253');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tallahassee', 'Florida', '32303');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Nashville', 'Tennessee', '37211');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bellingham', 'Washington', '98226');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Woodstock', 'Illinois', '60098');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Haltom City', 'Texas', '76117');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Wheeling', 'Illinois', '60090');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Summerville', 'South Carolina', '29483');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hot Springs', 'Arkansas', '71901');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Englewood', 'Colorado', '80112');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lancaster', 'Ohio', '43130');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Las Cruces', 'New Mexico', '88001');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hoover', 'Alabama', '35244');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Frisco', 'Texas', '75034');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Vacaville', 'California', '95687');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Murray', 'Utah', '84107');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Waukesha', 'Wisconsin', '53186');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bakersfield', 'California', '93309');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pompano Beach', 'Florida', '33068');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Troy', 'Ohio', '45373');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Corpus Christi', 'Texas', '78415');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Redondo Beach', 'California', '90278');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Orlando', 'Florida', '32839');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Orange', 'New Jersey', '7050');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lake Charles', 'Louisiana', '70601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Highland Park', 'Illinois', '60035');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hempstead', 'New York', '11550');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Noblesville', 'Indiana', '46060');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Apple Valley', 'Minnesota', '55124');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mount Pleasant', 'South Carolina', '29464');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Sterling Heights', 'Michigan', '48310');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Eau Claire', 'Wisconsin', '54703');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pharr', 'Texas', '78577');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Billings', 'Montana', '59102');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Gresham', 'Oregon', '97030');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chattanooga', 'Tennessee', '37421');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Meridian', 'Idaho', '83642');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Apple Valley', 'California', '92307');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bolingbrook', 'Illinois', '60440');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Maple Grove', 'Minnesota', '55369');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Woodland', 'California', '95695');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Missouri City', 'Texas', '77489');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pearland', 'Texas', '77581');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Mateo', 'California', '94403');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Grand Rapids', 'Michigan', '49505');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Visalia', 'California', '93277');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Overland Park', 'Kansas', '66212');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Temecula', 'California', '92592');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Yucaipa', 'California', '92399');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Revere', 'Massachusetts', '2151');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Conroe', 'Texas', '77301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tinley Park', 'Illinois', '60477');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dubuque', 'Iowa', '52001');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dearborn Heights', 'Michigan', '48127');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Santa Fe', 'New Mexico', '87505');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hickory', 'North Carolina', '28601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Carol Stream', 'Illinois', '60188');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Saint Cloud', 'Minnesota', '56301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'North Miami', 'Florida', '33161');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lawrence', 'Indiana', '46226');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Plantation', 'Florida', '33317');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Port Saint Lucie', 'Florida', '34952');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rock Hill', 'South Carolina', '29730');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Odessa', 'Texas', '79762');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'West Allis', 'Wisconsin', '53214');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chula Vista', 'California', '91911');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Manhattan', 'Kansas', '66502');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Altoona', 'Pennsylvania', '16602');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Thornton', 'Colorado', '80229');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Champaign', 'Illinois', '61821');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bloomington', 'Indiana', '47401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Texarkana', 'Arkansas', '71854');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Edinburg', 'Texas', '78539');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Baytown', 'Texas', '77520');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Greenwood', 'Indiana', '46142');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lakewood', 'California', '90712');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Woonsocket', 'Rhode Island', '2895');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Superior', 'Wisconsin', '54880');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bedford', 'Texas', '76021');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Covington', 'Washington', '98042');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Broken Arrow', 'Oklahoma', '74012');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Miramar', 'Florida', '33023');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hollywood', 'Florida', '33021');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Deer Park', 'Texas', '77536');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Wichita', 'Kansas', '67212');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mcallen', 'Texas', '78501');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Iowa City', 'Iowa', '52240');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Boise', 'Idaho', '83704');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cranston', 'Rhode Island', '2920');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Freeport', 'Illinois', '61032');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Port Arthur', 'Texas', '77642');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Citrus Heights', 'California', '95610');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'The Colony', 'Texas', '75056');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Redmond', 'Washington', '98052');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Daytona Beach', 'Florida', '32114');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bullhead City', 'Arizona', '86442');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Portage', 'Indiana', '46368');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Fargo', 'North Dakota', '58103');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Elkhart', 'Indiana', '46514');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Gabriel', 'California', '91776');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Margate', 'Florida', '33063');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Sandy Springs', 'Georgia', '30328');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mentor', 'Ohio', '44060');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lawton', 'Oklahoma', '73505');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hampton', 'Virginia', '23666');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rome', 'New York', '13440');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'La Crosse', 'Wisconsin', '54601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lewiston', 'Idaho', '83501');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hattiesburg', 'Mississippi', '39401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Danville', 'California', '94526');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mount Pleasant', 'Michigan', '48858');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Logan', 'Utah', '84321');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Waterbury', 'Connecticut', '6708');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Athens', 'Georgia', '30605');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lewiston', 'Maine', '4240');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Danville', 'Illinois', '61832');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Avondale', 'Arizona', '85323');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Marietta', 'Georgia', '30062');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Yuma', 'Arizona', '85364');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Wausau', 'Wisconsin', '54401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pasco', 'Washington', '99301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Oak Park', 'Illinois', '60302');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pensacola', 'Florida', '32503');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'League City', 'Texas', '77573');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Gaithersburg', 'Maryland', '20877');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lehi', 'Utah', '84043');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Tuscaloosa', 'Alabama', '35401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Moreno Valley', 'California', '92553');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Georgetown', 'Kentucky', '40324');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Loveland', 'Colorado', '80538');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chandler', 'Arizona', '85224');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Helena', 'Montana', '59601');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Kirkwood', 'Missouri', '63122');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Waco', 'Texas', '76706');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Roseville', 'Michigan', '48066');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Frankfort', 'Illinois', '60423');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bethlehem', 'Pennsylvania', '18018');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Roseville', 'Minnesota', '55113');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Grand Island', 'Nebraska', '68801');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Woodbury', 'Minnesota', '55125');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Oak Park', 'Michigan', '48237');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rogers', 'Arkansas', '72756');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Clovis', 'New Mexico', '88101');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Jupiter', 'Florida', '33458');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Santa Barbara', 'California', '93101');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cedar Hill', 'Texas', '75104');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Norfolk', 'Nebraska', '68701');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Draper', 'Utah', '84020');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Ann Arbor', 'Michigan', '48104');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'La Mesa', 'California', '91941');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pocatello', 'Idaho', '83201');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Holland', 'Michigan', '49423');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Milford', 'Connecticut', '6460');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Buffalo Grove', 'Illinois', '60089');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lake Forest', 'California', '92630');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Redding', 'California', '96003');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Chico', 'California', '95928');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Utica', 'New York', '13501');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Conway', 'Arkansas', '72032');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cheyenne', 'Wyoming', '82001');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Owensboro', 'Kentucky', '42301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Caldwell', 'Idaho', '83605');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Kenner', 'Louisiana', '70065');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Nashua', 'New Hampshire', '3060');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bartlett', 'Tennessee', '38134');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Redwood City', 'California', '94061');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lebanon', 'Tennessee', '37087');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Santa Maria', 'California', '93454');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Des Plaines', 'Illinois', '60016');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Longview', 'Washington', '98632');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hendersonville', 'Tennessee', '37075');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Waterloo', 'Iowa', '50701');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Cambridge', 'Massachusetts', '2138');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Palatine', 'Illinois', '60067');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Beverly', 'Massachusetts', '1915');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Eugene', 'Oregon', '97405');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Oxnard', 'California', '93030');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Renton', 'Washington', '98059');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Glenview', 'Illinois', '60025');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Delray Beach', 'Florida', '33445');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Commerce City', 'Colorado', '80022');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Texas City', 'Texas', '77590');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Wilson', 'North Carolina', '27893');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rio Rancho', 'New Mexico', '87124');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Goldsboro', 'North Carolina', '27534');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Everett', 'Washington', '98208');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Montebello', 'California', '90640');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'El Cajon', 'California', '92020');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Beaumont', 'Texas', '77705');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'West Palm Beach', 'Florida', '33407');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Abilene', 'Texas', '79605');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Normal', 'Illinois', '61761');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Saint Charles', 'Missouri', '63301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Saint Charles', 'Illinois', '60174');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Camarillo', 'California', '93010');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hillsboro', 'Oregon', '97123');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Burbank', 'California', '91505');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Modesto', 'California', '95351');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Garden City', 'Kansas', '67846');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Atlantic City', 'New Jersey', '8401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Longmont', 'Colorado', '80501');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Davis', 'California', '95616');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Wheeling', 'West Virginia', '26003');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Morgan Hill', 'California', '95037');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Clifton', 'New Jersey', '7011');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Sheboygan', 'Wisconsin', '53081');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'East Point', 'Georgia', '30344');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Rapid City', 'South Dakota', '57701');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Andover', 'Massachusetts', '1810');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Kissimmee', 'Florida', '34741');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Shelton', 'Connecticut', '6484');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Danbury', 'Connecticut', '6810');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Marion', 'Iowa', '52302');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Sanford', 'Florida', '32771');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Marcos', 'Texas', '78666');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Greeley', 'Colorado', '80634');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mansfield', 'Texas', '76063');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Elyria', 'Ohio', '44035');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Twin Falls', 'Idaho', '83301');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Coral Gables', 'Florida', '33134');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Romeoville', 'Illinois', '60441');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Marlborough', 'Massachusetts', '1752');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Laurel', 'Maryland', '20707');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Bryan', 'Texas', '77803');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Pine Bluff', 'Arkansas', '71603');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Aberdeen', 'South Dakota', '57401');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Hagerstown', 'Maryland', '21740');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'East Orange', 'New Jersey', '7017');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Arlington Heights', 'Illinois', '60004');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Oswego', 'Illinois', '60543');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Coon Rapids', 'Minnesota', '55433');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Clemente', 'California', '92672');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Dublin', 'California', '94568');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'San Luis Obispo', 'California', '93405');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Springdale', 'Arkansas', '72762');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Lodi', 'California', '95240');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'La Porte', 'Texas', '77571');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Mason', 'Ohio', '45040');
INSERT INTO Location (country, city, state, postal_code) VALUES ('United States', 'Woodstock', 'Georgia', '30188');

SELECT * FROM Location;

select * from Location
where city='Colorado'



